language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_install:
  - npm i -g npm@latest
before_script:
  - echo now before script
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script: 
  - echo now test finished
  - karma start
